### ISSUE TITLE
Please include a data dictionary

### ISSUE THREAD

**Issue by hanowell** [mihiriyer/gdxdata#1]
Thank you so much for providing this excellent VA expenditures data source. For those who are unfamiliar with the variables, would you please include a data dictionary or format the tables with variable descriptions in metadata? Even providing this PDF in a link would be helpful: https://www.va.gov/VETDATA/docs/GDX/GDX_Readme.pdf

**Comment by mihiriyer** [comment]
@BrashEQLibrium  My sincerest apologies for the delayed reply, I simply wasn't watching this repo. I wish I had a proper data dictionary. I've cobbled together some definitions for each of the expenditure variables. Take a look at the file named, GDX_Variable_Definitions.MD

Hope this helps!

**Comment by mihiriyer** [comment]
@BrashEQLibrium  My sincerest apologies for the delayed reply, I simply wasn't watching this repo. I wish I had a proper data dictionary. I've cobbled together some definitions for each of the expenditure variables. Take a look at the file named, GDX_Variable_Definitions.MD

Hope this helps!

**Comment by mihirasaraswati** [comment]
@BrashEQLibrium My sincerest apologies for the delayed reply, I simply wasn't watching this repo. I wish I had a proper data dictionary. I've cobbled together some definitions for each of the expenditure variables. Take a look at the file named, GDX_Variable_Definitions.MD

Hope this helps!
